# Generated by Django 5.0.4 on 2024-07-26 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aa', '0003_alter_rooms_username2'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='name',
            field=models.CharField(blank=True, max_length=23, null=True),
        ),
    ]
